function Write-AutoGeneratedInvocationMessages {
    <#
    .DESCRIPTION
        Writes a series of messages logging the function call.
    #>
    [OutputType([HashTable])]
    [CmdletBinding()]
    param ( [Parameter(Mandatory,ValueFromPipeline)] [HashTable] $MessageObject )

    process {

        try {

            Write-StatusMessage -Type 'Process' `
                                -PreSpace `
                                -Message $( 'Function Call: {0}' -f $MessageObject.TargetFunctionName )
                                
            Write-StatusMessage -Type 'Debug' `
                                -IndentationLevel 1 `
                                -Message $( 'Function File: {0}' -f $MessageObject.TargetFunctionFile )
                                
            Write-StatusMessage -Type 'Debug' `
                                -IndentationLevel 1 `
                                -Message $( 'Invocation Source: {0}, line {1}' -f $MessageObject.InvocationSource,
                                                                                  $MessageObject.InvocationLine)
                                
            Write-StatusMessage -Type 'Debug' `
                                -IndentationLevel 1 `
                                -Message $( 'Invocation File: {0}' -f $MessageObject.InvocationFile )
                                
        }
        catch {

            Write-ExceptionMessage -e $_

        }

    }
}
